base_model = "anthropic/claude-opus-4-8"
reasoning_options = [{ type = "effort", values = ["none", "low", "medium", "high", "xhigh", "max"] }]
name = "Claude-Opus-4.8"

[cost]
input = 4.2929
output = 21.4646
cache_read = 0.4293
cache_write = 5.3662

[limit]
context = 1_048_576
