name = "Google: Gemini 3.1 Flash Lite"
description = "Low-latency Gemini model for high-volume multimodal and agent workloads"
release_date = "2026-05-07"
last_updated = "2026-05-16"
attachment = true
reasoning_options = [{ type = "effort", values = ["low", "medium", "high", "xhigh"] }]
reasoning = true
tool_call = true
temperature = true
open_weights = false

[cost]
input = 0.12
output = 0.8
reasoning = 0.8
cache_read = 0.013
cache_write = 0.04167

[limit]
context = 1048576
output = 65536

[modalities]
input = ["audio", "image", "pdf", "text", "video"]
output = ["text"]
